theme: jekyll-theme-cayman
highlighter: rouge
name: LPIC 2 Vorbereitung
url: https://ogaida.github.io/lpic2/
markdown: kramdown

gems:
  -octopress-escape-code

# like described here https://adam.garrett-harris.com/how-to-redirect-pages-in-jekyll/ ...
collections:
  redirects:
    output: true
    permalink: /:path/
