theme: jekyll-theme-cayman

gems:
  -octopress-escape-code
  
# like described here https://adam.garrett-harris.com/how-to-redirect-pages-in-jekyll/
collections:
  redirects:
    output: true
    permalink: /:path/
